### ISSUE TITLE
IPv6 case is not considered when setting timeout

### ISSUE THREAD

**Issue by louielong** [KIodine/ping#1]
When ping IPv6 timeout the ping function doesn't raise an exception, the reason is 
`ping_once` function not  considered  to set timeout at IPv6 case
[ping_once] (https://github.com/KIodine/ping/blob/0cc6a09b7199f3bf2792c376cc418a4652d85824/ping/ping.py#L271-L272) 

The same as [ping_seq](https://github.com/KIodine/ping/blob/0cc6a09b7199f3bf2792c376cc418a4652d85824/ping/ping.py#L287) and [tracert](https://github.com/KIodine/ping/blob/0cc6a09b7199f3bf2792c376cc418a4652d85824/ping/ping.py#L505)

**Comment by KIodine** [comment]
Thanks for reporting! Seems you've fix this issue in the forked repository, a pull request is welcomed.

**Comment by KIodine** [comment]
[Pull request](https://github.com/KIodine/ping/pull/2) accepted, thanks for your contribution!
